var datas = [
    {
        id: 1,
        num: "001",
        title: "Кори Ниязова 1в2/4/6 Спец планировка (акай сити)",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 68000, 
        rooms: 2,   
        release_date: 1632827972348, 
        area: "60 m.kv",
        overview: "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
    },
    {
        id: 2,
        num: "002",
        title: "Продажа квартиры в новостройке",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/wyac6ia6z48m3-UZ/image;s=1000x700",
        type: ["Kvartira", "Yangi uylar"],
        price: 125000, 
        rooms: 3,   
        release_date: 1632827972948,
        area: "75 m.kv",
        overview: "Kvartirada bor: Muzlatkich, Televizor, Konditsioner, Kir yuvish mashinasi, Oshxona, Balkon",
    },
    {
        id: 3,
        num: "003",
        title: "Продаётся Евро Дом 2сот 5ком",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/cenn8yqp02ss2-UZ/image;s=1000x700",
        type: ["Yangi uylar", "Hovli"],
        price: 79999, 
        rooms: 5,   
        release_date: 1632825972348,
        area: "200 m.kv",
        overview: "Uyda / Uchastkada bor: Ertoʻla, omborcha, Garaj, Maishiy texnika, Kanalizatsiya, Tomorqa",
    },
    {
        id: 4,
        num: "004",
        title: "Аренда Abay Korzinga 3 хона оилага берилади",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/fmr29kbpl8jn1-UZ/image;s=1000x700",
        type: ["Kvartira", "Ijara"],
        price: 350, 
        rooms: 3,   
        release_date: 1652827972348,
        area: "78 m.kv",
        overview: "Kvartirada bor: Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Oshxona, Balkon",
    },
    {
        id: 5,
        num: "005",
        title: "Oilaga Shinam Xonadon",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/l4i7yeojo7hl1-UZ/image;s=1000x700",
        type: ["Hovli"],
        price: 49000, 
        rooms: 4,   
        release_date: 1632427972348,
        area: "200 m.kv",
        overview: "Kvartirada bor: Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona",
    },
    {
        id: 6,
        num: "006",
        title: "Продается земля на Юнусабаде,Шахристанский, ор. Муза центр.",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/s1e6dsn2chjn2-UZ/image;s=1000x700",
        type: ["Hovli", "Yer uchastkalar",],
        price: 14000, 
        rooms: 0,   
        release_date: 1632823972348,
        area: "500 m.kv",
        overview: "Kommunikatsiyalar: Elektr quvvati, Suv, Gaz, Isitish tizimi, Kanalizatsiya, Internet, Telefon",
    },
    {
        id: 7,
        num: "007",
        title: "Аренда Срочно!! ТРЦ Некст 1/2/4 Новый Евролюкс Full Аппартамент.",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/xtxdhc46ctf63-UZ/image;s=1000x700",
        type: ["Kvartira", "Ijara", "Yangi uylar",],
        price: 500, 
        rooms: 1,   
        release_date: 1632227972348,
        area: "50 m.kv",
        overview: "Аренда Срочно!! ТРЦ Некст 1/2/4 Новый Евролюкс Full Hi-Tech Аппартамент Цена: 500$",
    },
    {
        id: 8,
        num: "008",
        title: "Продается срочно квартира на Nest one 2/17/51 57м2",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        type: ["Kvartira", "Yangi uylar",],
        price: 97000, 
        rooms: 2,   
        release_date: 1632627972348,
        area: "57 m.kv",
        overview: "Yaqinida joylashgan: Kasalxona, poliklinika, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar, Park, yashil zona, Koʻngilochar muassasalar, Restoran, kafelar, turargoh, Supermarket, doʻkonlar, Maktab",
    },
    {
        id: 9,
        num: "009",
        title: "2х комн. кв. сдается в аренду. м. Х.Алимжана!!",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/ljrtkvtkjfuw2-UZ/image;s=1000x700",
        type: ["Kvartira", "Ijara",],
        price: 1500, 
        rooms: 2,   
        release_date: 1632827572348,
        area: "70 m.kv",
        overview: "Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona",
    },
    {
        id: 10,
        num: "0010",
        title: "ВЫГОДНОЕ ПРЕДЛОЖЕНИЕ Продажа Котеджи по доступной ЦЕНЕ в рассрочку",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/hqzxn9xn9mxw1-UZ/image;s=1000x700",
        type: ["Hovli", "Yangi uylar"],
        price: 140000, 
        rooms: 3,   
        release_date: 1632427972348,
        area: "209 m.kv",
        overview: "Связь Aloqa uchun +99890 928 09 88 отдела продаж Расположение/Manzil Ташкент, Зангиатинский район, улица Хамжихат  Адрес главного офиса отдела продаж, где вам дадут полную консультацию по всем интересующим вас вопросам: Ташкент, Ц1, улица Махтумкули, 48.",
    },
    {
        id: 11,
        num: "0011",
        title: "Большой новый особняк в элитном районе (Никитина с 6.5 сотками)",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/x2nupym3y7en1-UZ/image;s=1000x700",
        type: ["Hovli",],
        price: 800000, 
        rooms: 7,   
        release_date: 1632827972348,
        area: "1000 m.kv",
        overview: "Благоустройство дома: электричество, отопление, газ, водопровод +998908083663",
    },
    {
        id: 12,
        num: "0012",
        title: "Срочно Продаю Квартиру На Чиланзаре 20 Квартале 1/3/4",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/yo5ukolqc5gh3-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 13300, 
        rooms: 1,   
        release_date: 1632127972348,
        area: "19 m.kv",
        overview: "#Район - Чиланзар, 20 Возле Мечети Илон Ота Бывшее общежитие 1/3/4 , площадь 19 кв м² Внутри газовая плита Цена 13.000 $",
    },
    {
        id: 13,
        num: "0013",
        title: "(КМ103091) Продается помещение в Мирзо-Улугбекском районе.",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/g9lpcw5h52ni-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 1000000, 
        rooms: 1,   
        release_date: 1632857952348,
        area: "1000 m.kv",
        overview: "Koʻchmas mulk turi: Do’konlar/butiklar, Salonlar, Ofislar, Erkin maqsaddagi xona-joylar, Binoning bir qismi, Boshqa",
    },
    {
        id: 14,
        num: "0014",
        title: "Аренда Общежитие 1/3/4 Ялангач",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/gi64kyxfvlw32-UZ/image;s=1000x700",
        type: ["Kvartira", "Ijara",],
        price: 170, 
        rooms: 1,   
        release_date: 1631427972348,
        area: "30 m.kv",
        overview: "аренда квартира Район - мирзо Улугбек  Ориентир - Мирзо Улугбекская налоговая, кательная",
    },
    {
        id: 15,
        num: "0015",
        title: "Кора Ниязова 1в2/4/6 Спец планировка (акай сити)",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 68000, 
        rooms: 2,   
        release_date: 1632827972348,
        area: "60 m.kv",
        overview: "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
    },
    {
        id: 16,
        num: "0016",
        title: "Кора Ниязова 1в2/4/6 Спец планировка (акай сити)",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 68000, 
        rooms: 2,   
        release_date: 1632827972348,
        area: "60 m.kv",
        overview: "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
    },
    {
        id: 17,
        num: "0017",
        title: "Кора Ниязова 1в2/4/6 Спец планировка (акай сити)",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 68000, 
        rooms: 2,   
        release_date: 1632827972348,
        area: "60 m.kv",
        overview: "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
    },
    {
        id: 18,
        num: "0018",
        title: "Кора Ниязова 1в2/4/6 Спец планировка (акай сити)",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 68000, 
        rooms: 2,   
        release_date: 1632867972348,
        area: "60 m.kv",
        overview: "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
    },
    {
        id: 19,
        num: "0019",
        title: "Кора Ниязова 1в2/4/6 Спец планировка (акай сити)",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 68000, 
        rooms: 2,   
        release_date: 1632877972348,
        area: "60 m.kv",
        overview: "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
    },
    {
        id: 20,
        num: "0020",
        title: "S E R G E L I E L I T E",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/ynf6xndrfcrh1-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 450000, 
        rooms: 2,   
        release_date: 1632887972348,
        area: "60 m.kv",
        overview: "“S E R G E L I E L I T E” kvartiri rassrochka i kridit 20 let!",
    },
    {
        id: 21,
        num: "0021",
        title: "Азия Хаус",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/6v42pekhngjr-UZ/image;s=1000x700",
        type: ["Kvartira"],
        price: 21681, 
        rooms: 2,   
        release_date: 1632897972348,
        area: "62 m.kv",
        overview: "Азия Хаус последние квартири финиш скидок.Не упусти свой шанс",
    },
    {
        id: 22,
        num: "0022",
        title: "MFY Bobir shoh kochasi 11 uy",
        img: "https://apollo-olx.cdnvideo.ru/v1/files/b4p5h4dsv633-UZ/image;s=1000x700",
        type: ["Hovli",],
        price: 98000, 
        rooms: 7,   
        release_date: 1632997972348,
        area: "1000 m.kv",
        overview: "Uy sotiladi manzil Andijon shahri mustaqillik MFY Bobir shoh kochasi",
    },
]